# Generated by Django 2.0.6 on 2019-09-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=20, null=True)),
                ('book_counts', models.IntegerField(blank=True, null=True)),
                ('category_pid', models.IntegerField(blank=True, null=True)),
                ('column_5', models.CharField(blank=True, db_column='Column_5', max_length=20, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=128)),
                ('book_author', models.CharField(max_length=64)),
                ('book_publish', models.CharField(max_length=128)),
                ('publish_time2', models.DateField(blank=True, null=True)),
                ('revision2', models.IntegerField(blank=True, null=True)),
                ('book_isbn', models.CharField(blank=True, max_length=64, null=True)),
                ('word_count2', models.CharField(blank=True, max_length=64, null=True)),
                ('page_count2', models.IntegerField(blank=True, null=True)),
                ('open_type2', models.CharField(blank=True, max_length=20, null=True)),
                ('book_paper', models.CharField(blank=True, max_length=64, null=True)),
                ('book_wrapper', models.CharField(blank=True, max_length=64, null=True)),
                ('book_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('book_dprice', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('editor_recommendation', models.CharField(blank=True, max_length=2000, null=True)),
                ('content_introduction', models.CharField(blank=True, max_length=2000, null=True)),
                ('author_introduction', models.CharField(blank=True, max_length=2000, null=True)),
                ('menu2', models.CharField(blank=True, max_length=2000, null=True)),
                ('media_review2', models.CharField(blank=True, max_length=2000, null=True)),
                ('digest_image_path2', models.CharField(blank=True, max_length=2000, null=True)),
                ('product_image_path', models.CharField(blank=True, max_length=2000, null=True)),
                ('series_name', models.CharField(blank=True, max_length=128, null=True)),
                ('printing_time', models.DateField(blank=True, null=True)),
                ('impression', models.CharField(blank=True, max_length=64, null=True)),
                ('stock2', models.IntegerField(blank=True, null=True)),
                ('shelves_date', models.DateField(blank=True, null=True)),
                ('customer_socre', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('book_status', models.IntegerField(blank=True, null=True)),
                ('sales', models.IntegerField(blank=True, null=True)),
                ('column_27', models.CharField(blank=True, db_column='Column_27', max_length=20, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('products_count', models.IntegerField(blank=True, null=True)),
                ('column_7', models.CharField(blank=True, db_column='Column_7', max_length=20, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'goods_car',
            },
        ),
        migrations.CreateModel(
            name='GoodsOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField()),
                ('num', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('column_8', models.CharField(blank=True, db_column='Column_8', max_length=20, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'goods_order',
            },
        ),
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_num', models.IntegerField()),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('column_6', models.CharField(blank=True, db_column='Column_6', max_length=20, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'orderitem',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_mail', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('user_status', models.IntegerField()),
                ('column_8', models.CharField(blank=True, db_column='Column_8', max_length=20, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id2', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('detail_address', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('telphone', models.CharField(blank=True, max_length=20, null=True)),
                ('addr_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('column_6', models.CharField(blank=True, db_column='Column_6', max_length=20, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'user_address',
            },
        ),
    ]
